### ISSUE TITLE
Trying to import manny as gltf for testing but the model is importing distorted

### ISSUE THREAD

**Issue by JasperCatStudios** [rdeioris/glTFRuntime#101]
![failedimport](https://github.com/user-attachments/assets/f7395e7d-a850-4b86-be07-e0298080ef58)
![gltfbp](https://github.com/user-attachments/assets/29659eba-cd2c-4728-9a52-6b07c3463130)

I exported from blender using the gltf embedded settings from the documentation. The skeletons are identical so I dont understand the issue.

**Comment by rdeioris** [comment]
Please share the asset, thanks

**Comment by JasperCatStudios** [comment]
uploaded the material is just different because i was testing on how to edit it in blender
https://drive.google.com/file/d/1-hecqIzFnX2nNIbNPsrZ0aQVD8pEZqXc/view?usp=sharing

**Comment by rdeioris** [comment]
Your model is (correctly) using the GLTF axis convention, while the unreal one (quinn) has y-forward configuration. Just instruct the loader to use y-forward:

![image](https://github.com/user-attachments/assets/9808dc0e-f8ed-43a8-8ade-7e9b6bcf55e0)

**Comment by JasperCatStudios** [comment]
Thank you its working now! :D

**Comment by JasperCatStudios** [comment]
Sorry, another issue occured when using a different model rigged with auto rig pro for unreal manny. I also tried auto rig pro gltf export with the same result. If I import the fbx in the editor it can use the manny skeleton just fine. I tried y forward and all the options in that loader configuration. I uploaded the mesh if you want to test it out. https://drive.google.com/file/d/151HI6Y2oSF9csr1DmijfptaRAJwXzBuA/view?usp=sharing

**Comment by rdeioris** [comment]
Please check the two tutorials about retargeting first as it is a complex topic (in any case you have not provided the .bin file so i cannot open the asset):

https://github.com/rdeioris/glTFRuntime-docs/tree/master/Tutorials

**Comment by JasperCatStudios** [comment]
Should I create a remap json even though the bone names are all the same? I noticed the bones were rotated differently when I imported it into blender but I dont know how to fix it. Clear rotation and copy rotation didnt work. Here is the bin link:https://drive.google.com/file/d/1J2tLcI4_7PpR6-6CTkS_0f1cTbiSccK4/view?usp=sharing

**Comment by rdeioris** [comment]
The poses are mostly incompatible (A-Pose vs T-Pose). You can copy the rotations (remember to remove Overwrite Ref Skeleton) and it will more-or-less work (obviously elbows will be completely broken, but in the tutorials is explained how to overcome it).

If the name mappings are the same you do not need to remap them (or use a json).
