### ISSUE TITLE
UE 5.5.0 Compile Failure

### ISSUE THREAD

**Issue by acottam1** [rdeioris/glTFRuntime#104]
The compile for UE 5.5.0 fails at glTFRuntimeParserSkeletalMeshes.cpp
The glTFRuntimeParserSkeletalMeshes.cpp file is the only one that appears to be failing to compile.

`[28/48] Compile [x64] glTFRuntimeParserSkeletalMeshes.cpp
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1190): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1193): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1193): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1194): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1194): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1195): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1195): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1196): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1196): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1197): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1197): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1245): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1246): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1247): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1248): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1257): error C2065: 'FKSphylElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1257): error C2146: syntax error: missing ';' before identifier 'Capsule'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1257): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1261): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1262): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1263): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1268): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1269): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1270): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1274): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1276): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1277): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1280): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1280): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1284): error C2065: 'FKSphereElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1284): error C2146: syntax error: missing ';' before identifier 'Sphere'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1284): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1286): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1287): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1289): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1289): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1293): error C2065: 'FKBoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1293): error C2146: syntax error: missing ';' before identifier 'BoxElem'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1293): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1295): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1297): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1298): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1299): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1301): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1301): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1326): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1327): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1328): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1329): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1333): error C2065: 'FKSphylElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1333): error C2146: syntax error: missing ';' before identifier 'Capsule'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1333): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1334): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1335): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1336): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1337): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1338): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1338): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1343): error C2065: 'FKSphereElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1343): error C2146: syntax error: missing ';' before identifier 'Sphere'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1343): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1344): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1345): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1346): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1346): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1351): error C2065: 'FKBoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1351): error C2146: syntax error: missing ';' before identifier 'Box'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1351): error C2065: 'Box': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1352): error C2065: 'Box': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1353): error C2065: 'Box': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1354): error C2065: 'Box': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1355): error C2065: 'Box': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1356): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1356): error C2065: 'Box': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1378): error C2065: 'FKSphereElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1378): error C2146: syntax error: missing ';' before identifier 'Sphere'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1378): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1380): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1381): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1383): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1383): error C2065: 'Sphere': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1404): error C2065: 'FKBoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1404): error C2146: syntax error: missing ';' before identifier 'BoxElem'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1404): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1406): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1408): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1409): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1410): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1411): error C2027: use of undefined type 'USkeletalBodySetup'
C:\Program Files\Epic Games\UE_5.5\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\PhysicsAsset.h(20): note: see declaration of 'USkeletalBodySetup'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1411): error C2065: 'BoxElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1432): error C2065: 'FKSphylElem': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1432): error C2146: syntax error: missing ';' before identifier 'Capsule'
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1432): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1436): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1437): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1438): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1443): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1444): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1445): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1449): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1451): error C2065: 'Capsule': undeclared identifier
C:\Plugins\HostProject\Plugins\glTFRuntime\Source\glTFRuntime\Private\glTFRuntimeParserSkeletalMeshes.cpp(1451): fatal error C1003: error count exceeds 100; stopping compilation`

**Comment by rdeioris** [comment]
Getting the same errors from Epic build pipeline, definitely some missing headers. i will check it asap. Thanks for reporting.

**Comment by rdeioris** [comment]
Should be fixed in master

**Comment by acottam1** [comment]
Thanks for your help, can confirm it is working now!
