### ISSUE TITLE
Unable to load POSITION attribute

### ISSUE THREAD

**Issue by ArmainAP** [rdeioris/glTFRuntime#13]
Hello! If you export any .gltf model using [glTF Exporter](https://www.unrealengine.com/marketplace/en-US/product/gltf-exporter) and default settings you will encounter the following error:
`LogGLTFRuntime: Error: LoadPrimitive(): Unable to load POSITION attribute`

Steps to reproduce:
1. Export any model using [glTF Exporter](https://www.unrealengine.com/marketplace/en-US/product/gltf-exporter) 
2. Try to import it using glTFRuntime

Additional note: The issue seems to be encountered only with .gltf models and .glb models work as expected.

Thank you very much!

**Comment by rdeioris** [comment]
@ArmainAP for security reasons loading external files is disabled by default. You can enable it from the loader config structure. Notice btw that embedded gltf and glb are the best supported ones (as they work even in http mode)

**Comment by ArmainAP** [comment]
>  You can enable it from the loader config structure
Do you mean bSearchContentDir?
I have it set on true and I encounter the same issue.

**Comment by rdeioris** [comment]
@ArmainAP this one: 
![immagine](https://user-images.githubusercontent.com/2234592/127904774-890755c6-ddbe-4ff1-9753-d825845833e7.png)
 flag "Allow External Files" to load them

**Comment by ArmainAP** [comment]
I was running an outdated version, sorry. I updated it to be on par with current master.
After I enabled it, everything worked as expected. Thank you very much!
