### ISSUE TITLE
MaterialsOverrideMap not working

### ISSUE THREAD

**Issue by lichenbo** [rdeioris/glTFRuntime#16]
I've tried to use the MaterialsOverrideMap to override the materials at runtime, but it seems not working. I checked the source code and didn't find the implementation. Is it a mistake or I'm using it wrongly?

**Comment by rdeioris** [comment]
Thanks for reporting, fixed with this commit: https://github.com/rdeioris/glTFRuntime/commit/b73cbc249e06ff7d6de645699b851b48c49a65d7
