### ISSUE TITLE
Plugin crash when spawn specific model

### ISSUE THREAD

**Issue by lichenbo** [rdeioris/glTFRuntime#18]
Hi, I'm recently testing to load some models from the repo https://github.com/KhronosGroup/glTF-Asset-Generator. This model https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Positive/Node_Attribute/Node_Attribute_00.gltf will immediately crash in Windows UE4.26 when spawned with the latest plugin.

**Comment by rdeioris** [comment]
Should be fixed in latest master
