### ISSUE TITLE
Some features not supported by the plugin

### ISSUE THREAD

**Issue by lichenbo** [rdeioris/glTFRuntime#19]
Hi, I'm recently experimenting the plugin with models from https://github.com/KhronosGroup/glTF-Asset-Generator

There are a few test failed with the feature test. I wonder if it's because of the plugin or my scenes. All the tests are conducted under Windows 10 UE 4.26

1.  Model #00 of the https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Instancing. Being loaded with the plugin, the model is not sampled with `CLAMPED_TO_EDGE `or `MIRRORED_REPEAT`, but showing as the default 'REPEAT' behaviour. Seems those texture samplers are not supported in the plugin yet?

2. Most models in https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Mesh_PrimitiveMode are failing. Looks like only the `Triangle` Primitive mode is supported by the plugin.

3. I see in the plugin description that Vertex Color is supported. But the models in https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Mesh_PrimitiveVertexColor are not showing up correctly in my UE4 editor. They looks white and not being applied to any vertex color. 

Thanks.

**Comment by rdeioris** [comment]
Hi @lichenbo thanks for the report:

1. Samplers are still not supported (but should be an easy addition for both wrapping and filtering)
2. Unreal only supports triangles, while it is not a huge problem to support STRIP and FAN too it can slowdown the load (as it needs to rebuild indices). Maybe an option for explicitely allowing them (or a performance warning) can be useful
3. This is weird, i will give it a look

**Comment by lichenbo** [comment]
Thank you for the quick reply :) 

Another potential issue is related to the implementation of specular glossiness. During my test on these objects (https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Material_SpecularGlossiness), the specular reflection are not as expected. I dig into the material a bit, and seems the renderer is always using the `specularFactor` value from MaterialConfig, instead of reading the vector from GLTF. Could you take a look as well?

**Comment by rdeioris** [comment]
Closing this as lot of new extensions and features have been implemented since the opening of the issue (included the ones reported)
