### ISSUE TITLE
Memory corruption when using the loader

### ISSUE THREAD

**Issue by sasmaster** [rdeioris/glTFRuntime#20]
Hello!
First, thanks for this awesome work. 
I am building an app where gltf model is loaded by user from file system. Since I started testing the whole functionality I am hitting inconsistent crashes in different subsystems and now I am quite sure that behavior happens ONLY when gltf has been loaded.For example, I have an audio/video encoder which runs flawlessly. Once I load gltf model,then call the encoder. The encoder fails on just opening a video stream,while the file path is completely valid and used in other sessions without crash. From my experience developing with C++ such a behavior is usually result of multi-threaded logic flaws, or runtime memory corruption which can be result of buffer overruns etc. My application code doesn't use threads. Game/rendering thread and anything that UE creates in the background is all I have. Maybe the model I am loading has data in it that causes the gltf parser to run outside the buffers bounds? I can't share the app but I can provide the code from the logic I use to load gltf and the model I am using. Thanks!

**Comment by rdeioris** [comment]
Hi the only part using threads is the skeletalmesh async loader, but in such a case you should check by just using the non-async functions. All of the other gTFRuntime functions are blocking. If you can post the glTFRuntime related code i can check if there is something wrong (please specify the platform you are working on too)

**Comment by rdeioris** [comment]
Closing as most of the code has been rewritten in the past year (included heavy usage of multithreading)
