### ISSUE TITLE
AglTFRuntimeAssetActorAsync: Complex collisions not working after Package 

### ISSUE THREAD

**Issue by ilike9527** [rdeioris/glTFRuntime#21]
Loading static mesh into "AglTFRuntimeAssetActorAsync", with "Allow CPUAccess" checked and "Use Complex Collision As Simple".

Functions like "LineTraceForObjects" work fine in the editor, but after the "Development" package they're not working at all.

UE 4.26, Windows 64.

Above functions work fine for ""AglTFRuntimeAssetActor"

Thanks.

**Comment by whucj** [comment]
I also have encountered the same problem, how can I solve it?

**Comment by rdeioris** [comment]
@ilike9527 thanks for reporting. Investigating this

**Comment by rdeioris** [comment]
Fixed in latest master
