### ISSUE TITLE
Run crash directly after packed in shipping mode in UE5  

### ISSUE THREAD

**Issue by whucj** [rdeioris/glTFRuntime#22]
Hello.
I want to use the plugin in UE5. But the program crashes when running after packed in shipping mode.

**Comment by rdeioris** [comment]
Does it happen in development/debug mode too ? If yes, can you send the traceback ?

**Comment by whucj** [comment]
It's ok in development mode.

**Comment by whucj** [comment]
I am very sorry, this crash is not caused by this plugin. Actually caused by other plugins. Thanks very much
