### ISSUE TITLE
Unreal 5.0.1 Bug

### ISSUE THREAD

**Issue by leielyq** [rdeioris/glTFRuntime#32]
Models cannot be loaded dynamically after compiling using the release mode

**Comment by leielyq** [comment]
sry.

**Comment by leielyq** [comment]
No schema compilation can be loaded dynamically.
The model can be loaded dynamically normally only in editor mode.

**Comment by rdeioris** [comment]
@leielyq Check the logs, very probably you are missing materials packaging

**Comment by leielyq** [comment]
@nsdfxela  Where are the logs? Thanks for the reply

**Comment by leielyq** [comment]
@nsdfxela   LogUObjectGlobals: Warning: Failed to find object 'MaterialInterface None./glTFRuntime/M_glTFRuntimeBase'

**Comment by rdeioris** [comment]
Check here: https://github.com/rdeioris/glTFRuntime-docs#notes-when-packaging-a-game how to force the inclusion of materials

**Comment by leielyq** [comment]
@nsdfxela    Good work!!!!
