### ISSUE TITLE
Bad MeshDescription

### ISSUE THREAD

**Issue by Flone-dnb** [rdeioris/glTFRuntime#35]
Hello!

I've wrapped glTFRuntime actor in a Blueprint in a way that the blueprint inherits from my slightly modified `AglTFRuntimeAssetActor` and stores relative path to the `.glb` asset. The Blueprint just calls scene loading (from `.glb`) on `BeginPlay` and `PostActorCreated`. With this I can drag'n'drop this blueprint to a scene and use it as a regular Unreal asset.

The problem is that with this approach when the model is loaded and displayed in the editor, the editor tries to cache static mesh data (when you start PIE with this asset in the scene or press "Compile" on Blueprint (with this asset in the scene)) and fails to do so because mesh description is not valid.

Engine/Source/Runtime/Engine/Private/StaticMesh.cpp, line 2823 on UE5:
`checkf(Owner->IsMeshDescriptionValid(0), TEXT("Bad MeshDescription on %s"), *GetPathNameSafe(Owner));`

This function checks for static mesh source models but I've checked the plugin does not create such (when parsing static mesh data). I've tried marking actor/components as transient in this case, tried loading empty mesh description, marking package as `bIsCookedForEditor` but this does not solve the issue.

I'm using Duck model from [glTF samples](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF-Binary).

I have very little knowledge in underling data used for static meshes in UE, thus I've decided to ask if you have any idea on how to fix this.

**Comment by rdeioris** [comment]
Hi MeshDescription is basically of no use out of the editor and it requires time to be generated. Fun fact, in older glTFRuntime releases the MeshDescription was the way staticmeshes were created (before moving to pure RHI structures). If you want you can check older releases (first months of 2021) to see if you can copy some part of the old code.

**Comment by Flone-dnb** [comment]
Got it, I will see what I can achieve with this tomorrow.

**Comment by Flone-dnb** [comment]
Update.

I'm using `glTFRuntime-20201222` version to generate mesh (it's using `MeshDescription` for that), but mesh generation code causes some asserts to be triggered, specifically this function: 
```C++
FStaticMeshOperations::ComputePolygonTangentsAndNormals(MeshDescription->GetMeshDescription());
```
causes some asserts, but it's marked as deprecated so I've replaced it with:
```C++
FStaticMeshOperations::ComputeTriangleTangentsAndNormals(MeshDescription->GetMeshDescription());
```
This causes no asserts but the mesh is not visible (probably not generated properly).

I then decided to do the following:
- generate new mesh as usual (using new glTFRuntime code),
- generate old mesh using old glTFRuntime code (using `MeshDescription`),
- copy `SourceModels` from old mesh to the new one, using the following code:
```C++
UStaticMesh* StaticMesh = Asset->LoadStaticMesh(Node.MeshIndex, StaticMeshConfig);
StaticMesh->SetSourceModels(
    Asset->LoadStaticMeshUsingMeshDescription(
        Node.MeshIndex, StaticMeshConfig)->MoveSourceModels());
```

And it works like a charm! No crashes, no asserts, no warnings.
Thanks for the tip!

**Comment by rdeioris** [comment]
@Flone-dnb feel free to link to a gist (or your own repository) here. If some users will have the same issue it can be of help and maybe i can evaluate if adding an option for generating meshdescriptions can be worthy to have in the main branch

**Comment by Flone-dnb** [comment]
@rdeioris We've modified the plugin for our needs, I can't share any code because the project is under NDA, sorry. But the only things I did is:
- copied old `FglTFRuntimeParser::LoadStaticMesh_Internal` from `glTFRuntime-20201222` and wrapped it with a new function `LoadStaticMeshUsingMeshDescription` (just like the usual `LoadStaticMesh`),
- added some `FVector`/`FVector3f` casts,
- replaced `FStaticMeshOperations::ComputePolygonTangentsAndNormals(MeshDescription->GetMeshDescription());` with `FStaticMeshOperations::ComputeTriangleTangentsAndNormals(MeshDescription->GetMeshDescription());`
- and added this:
```C++
UStaticMesh* StaticMesh = Asset->LoadStaticMesh(Node.MeshIndex, StaticMeshConfig);
StaticMesh->SetSourceModels(
    Asset->LoadStaticMeshUsingMeshDescription(
        Node.MeshIndex, StaticMeshConfig)->MoveSourceModels());
```
in `AglTFRuntimeAssetActor::ProcessNode` method.
You can try for our own.

**Comment by rdeioris** [comment]
@Flone-dnb MeshDescription generation has been added in master (you will find the option in StaticMeshConfig struct)

**Comment by Flone-dnb** [comment]
@rdeioris Oh great! Are you planning a release soon? I will talk this over with my team next week because we also had some troubles with animation (crashes on some GLTF assets).

**Comment by rdeioris** [comment]
@Flone-dnb new version (20220823) has been just released
