### ISSUE TITLE
Imported gltf static geometry not seen in Movie Render Queue (in the packaged game)

### ISSUE THREAD

**Issue by RaiaN** [rdeioris/glTFRuntime#36]
Hi @rdeioris !

I'm trying to set up a simple scene where .gltf file (contains static geometry only) being imported at runtime and then use Movie Render Queue to render one frame.

It is working fine in Editor but not in the packaged game. Not sure what is going on there. Engine static meshes work fine in both Editor and at Runtime. Could you please help?

**Comment by rdeioris** [comment]
@RaiaN are you sure you followed all of the steps (especially packaging materials) described here https://github.com/rdeioris/glTFRuntime-docs#notes-when-packaging-a-game ?

**Comment by RaiaN** [comment]
@rdeioris I've tried to use HighResolutionScreenshot in the packaged game and I see the same issue - there is no imported GLTF scene in the screeshot. You can quickly test this set up. 

I believe that is more general issue of runtime constructed static meshes...

**Comment by rdeioris** [comment]
@RaiaN quick addition: skeletal meshes works fine so as a temporary workaround you can force static meshes as skeletal:

![image](https://user-images.githubusercontent.com/2234592/173015950-d78a8da4-ea03-4cfe-af50-32ff8c35f4b7.png)

**Comment by rdeioris** [comment]
@RaiaN found the issue: StaticMeshes do not set LOD screen sizes when only one lod is in use. I have fixed it in latest branch but if you cannot update this is a quick workaround:

![image](https://user-images.githubusercontent.com/2234592/173021785-d6ecb43c-fa35-4645-94b0-8bf5c53e748d.png)

**Comment by RaiaN** [comment]
@rdeioris WOW, dude! Thanks so much! I'm going to try it shortly

**Comment by rdeioris** [comment]
hi, pulling from master should be enough
