### ISSUE TITLE
Plugin didn't work !

### ISSUE THREAD

**Issue by baraakhateeb** [rdeioris/glTFRuntime#37]
My Unreal Engine **v5.0.2**
![image](https://user-images.githubusercontent.com/54423291/174275919-1f60bfac-4fca-490b-af29-f8a052ca790e.png)
![image](https://user-images.githubusercontent.com/54423291/174276013-9df9e944-dab9-4457-b213-c316fcc1612a.png)

**Comment by rdeioris** [comment]
Hi, please use the Discord server for installation help. Btw, you need to start from a C++ project, generate the solution and the build it. More infos here: https://github.com/rdeioris/gltfruntime-docs#quickstart

**Comment by rdeioris** [comment]
@godefv on which platform ? thanks

**Comment by godefv** [comment]
I am on Windows 10.
