### ISSUE TITLE
Loading model animation, there will be flickering

### ISSUE THREAD

**Issue by leielyq** [rdeioris/glTFRuntime#40]
I don't speak English, I used a translator.
I have a problem, when loading this [model](http://leiel.dns.army:5000/sharing/CTgeHuAyB), everything works fine.
However, when the specified [model ](http://leiel.dns.army:5000/sharing/u5Ky4qhy3)is loaded, the model will flicker. I tried to use the screen recording tool to record the situation encountered, but there will be no flickering in the recorded video.
So I speculate whether it is related to the frame rate of model animation.
I desperately need your help.

**Comment by rdeioris** [comment]
Sorry the provided links are unreachable
