### ISSUE TITLE
Transform Bone in loaded glTF

### ISSUE THREAD

**Issue by qhanson** [rdeioris/glTFRuntime#41]
hi, using this plugin can load glTF file wonderfully. However, how to modify the bone in the loaded glTF.
When I create one animation graph, how to bind it to the loaded glTF?

**Comment by rdeioris** [comment]
This tutorial should help you: https://github.com/rdeioris/glTFRuntime-docs/blob/master/Tutorials/RetargetingRPMAndMixamo.md

**Comment by qhanson** [comment]
Thanks. This tutorial will help.  If I know this before, things will be easier.
I have finished loading one ReadyPlayerMeglb and driving it real-time with Livelink in one packaged testing render for supporting one demo. 
I remember several suffering problems as follows:
1. Modify curve in UE5.0.3 is not working while Modify Bone is working well in this version.
2. Load the skeletal from ReadyPlayerMe Plugin content directory. When loading the GLB with this plugin, just bind the skeletal to the loaded skeletal mesh.  Assign it with one animation blueprint with the previous skeletal. **#The official ReadyPlayerMe plugin based on this project is a good reference#**
