### ISSUE TITLE
Difference in material colours between Linux and Windows builds

### ISSUE THREAD

**Issue by matthew-rimmer** [rdeioris/glTFRuntime#52]
There seems to be some difference in how material colours are read in Linux as opposed to Windows builds. Here is a scene in the windows build:
![GoodModels](https://user-images.githubusercontent.com/40692294/212368093-d994890e-77e7-4972-a2c1-141181b2c462.png)

Linux build in the same scene, same models loaded:
![BadModels](https://user-images.githubusercontent.com/40692294/212368100-7648aced-9781-47a1-920d-0d8cd6fed9e8.png)

I assumed this was once vertex colour but upon inspecting the model it seemed to be a material colour. The models in windows seem to have their baseColorFactor correctly applied but I can only assume here it is not.

**Comment by katehryhorenko** [comment]
Hey! I believe I found the issue. All textures have a source file like this:
![image](https://user-images.githubusercontent.com/88673491/231548670-6fa708e5-4e2a-422c-b7c6-a4f27939a172.png)

I rebuilt texture with my local white.png image and it works.

**Comment by Rakurai** [comment]
I'm having the same issue on a Mac, but reimporting with a white 1x1 PNG still shows as a red texture?

**Comment by rdeioris** [comment]
Hi, in latest master i have changed the default textures to be 2x2. This should fix the issue

**Comment by ephb** [comment]
I had the issue too with the version from marketplace here on mister it is fixed.
