### ISSUE TITLE
Unreal 5.2 is not supported

### ISSUE THREAD

**Issue by KungFuDonkey** [rdeioris/glTFRuntime#53]
Currently, in the new source version of Unreal (5.2), GltfRuntime does not compile due to some changes to skeletal meshes in the engine. Most, of the issues, can be fixed by including Engine/SkinnedAssetCommon.h in glTFRuntimeParserSkeletalMeshes.cpp, as most of the objects of skinned assets were moved there. Also AudioExtensions needs to be added to the Build.cs file.

However the function AnimSequence->GetDataModel()->PostDuplicate(false); was also moved in the data model of AnimSequence. This function was used in glTFRuntimeParserSkeletalMeshes.cpp as a hack to call GenerateTransientData(), a function removed in Unreal 5.1. Now I do not know why this function needs to be called, but an alternative solution must be found if this is still needed.

I put all of these suggested changes in PR #54

**Comment by ffreality** [comment]
that .cpp file requires #include "Engine/SkeletalMeshLODSettings.h" I added and created a pull request. I can use it right now.
You can try it yourself

https://github.com/rdeioris/glTFRuntime/pull/67/commits/7414e54510c96d8d09a2d66e3a1ac74c2610df26
