### ISSUE TITLE
Morph targets not imported correctly with multiple bodies

### ISSUE THREAD

**Issue by RobinKa** [rdeioris/glTFRuntime#6]
Hey, thanks for the great plugin!

It looks like the morph targets don't get imported correctly when using `Load Skeletal Mesh Recursive Async` on gltf/glb files that have multiple bodies in them. Here's the file I used 
[G-ShepPubllicFemale.zip](https://github.com/rdeioris/glTFRuntime/files/6292989/G-ShepPubllicFemale.zip) (free model from here https://sketchfab.com/3d-models/german-shepherd-vrchat-ready-1068591ad6694c2c84b581805f87a6ee).

They work fine when I drop it here https://gltf-viewer.donmccurdy.com/

**Comment by rdeioris** [comment]
@RobinKa unfortunately the way MorphTargets work in Unreal is pretty 'strict'. In the discord channel you should find a bunch of workaround for it (mainly adding suffixes)

**Comment by rdeioris** [comment]
Closing as multiple import modes/strategies for morphtargets have been added during the years
