### ISSUE TITLE
The default SpecularFactor value should be 0.5

### ISSUE THREAD

**Issue by EvenZHAnglll** [rdeioris/glTFRuntime#61]
The default specular value is usually 0.5 in a PBR material.

When I import a gltf file in runtime, the default specular is 0, lead to incorrect rendering results.

The default SpecularFactor value is hardcoded to 0 in glTFRuntimeParser.h. It should be 0.5.

**Comment by rdeioris** [comment]
Hi, this is something that has been heavily discussed multiple times (but without meaningful results, to the point that there is a specific parameter for setting the default specular value). Do you have some official reference about that 0.5 ? because whenever that value is changed some user is pissed off ;)

**Comment by EvenZHAnglll** [comment]
In both Unreal Engine and Blender, the default value for specular in the default material is 0.5.

Offical Docs:
[Physically Based Materials in Unreal Engine | Unreal Engine Documentation](https://docs.unrealengine.com/5.0/en-US/physically-based-materials-in-unreal-engine/#:~:text=Roughness%20vs.%20Specular,the%20Roughness%20map.)
[Principled BSDF - Blender Manual](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/principled.html)

Other reference:
[A technical explanation on blender Stack Exchange](https://blender.stackexchange.com/questions/290596/what-do-i-set-specular-to-on-principled-bsdf#:~:text=The%20specular%20slider,for%20most%20materials.)

**Comment by rdeioris** [comment]
Sorry, i was referring to GLTF specs statements. By the way, at the end, given that we know the behaviour of some of the generatos, i have added the logic for forcing it to 0.5 in case of Unreal and Blender. Users can extend that part of the code or just use the new GetGenerator() node to manually set the specular factor:

https://github.com/rdeioris/glTFRuntime/commit/6b01f06942de68c6d03cb70ac784a772935859a2

Given that glTFRuntime as well as Blender support KHR_materials_specular too, this should fully cover (at least) Blender:
 default 0.5, or override via KHR_materials_specular (or brutally directly in glTFRuntime)

**Comment by rdeioris** [comment]
Closing as current code takes into account the (known) specular factors based on the generator software (included blender to 0.5)
