### ISSUE TITLE
can't find the way :  "complex collision as simple" don't work on Android

### ISSUE THREAD

**Issue by surfufu** [rdeioris/glTFRuntime#65]
Hi, 

I use LoadStaticMesh to convert to a StaticMesh and not GLTFRuntimeAssetActor ...   this maybe the issue ?  i need this kind of collision for the game, what i can do ? 
Is it possible to use UCX_ like for FBX ? 

thank you

**Comment by surfufu** [comment]
i don't understand what i need to do with the outer, look like i need to put it but i don't understand what is used for.

**Comment by rdeioris** [comment]
The outer requirement is to overcome a check made in epic code, it has no true usefulness in gltfruntime, so just set it to a valid uobject (like the staticmeshcomponent, or the level itself)

**Comment by surfufu** [comment]
Thank you for the response, i make it work on PC but it still not work on Android ...  (in the quest 2 in fact) ...  i find on internet that some peoples was able to use this feature by using an FBX with  "UCX_" mesh name of an other mesh inside (so one mesh for the graphical data and one mesh for the physics inside the same FBX) (but it's possible the issue are not the same: they do that in import in the editor not in realtime ... ) so i don't know if a solution exist to have complex collision as simple for android that work ... any idea ?

**Comment by surfufu** [comment]
In fact it would be perfect to be able to be able to set a custom collision mesh in Realtime ...

**Comment by rdeioris** [comment]
https://github.com/rdeioris/glTFRuntime/blob/master/Source/glTFRuntime/Private/glTFRuntimeParserStaticMeshes.cpp#L23

check this line, on UE4 the cpu access on mobile used to be broken, i have no way now to test it (i am on vacation) but try removing that line and retrying (maybe it is not an issue anymore on UE5).

**Comment by rdeioris** [comment]
This has been fixed in latest master, but requires UE 5.4 (previous versions have issues with CPU access of GPU related structures)
