### ISSUE TITLE
Several materials incompatible with 4.25

### ISSUE THREAD

**Issue by jimsimonz** [rdeioris/glTFRuntime#7]
M_glTFRuntime_SG_Base and other *sg* materials don't load in 4.25, they do load in 4.26. 

This means some materials are missing and packaging fails in 4.25 if these files are present.

Is it possible to resave these for 4.25.

**Comment by jimsimonz** [comment]
using this commit https://github.com/rdeioris/glTFRuntime/commit/56cb0cfc747c4df17bcb971f25e46fb62457b4d8#diff-47bd29075f8b8019f0beec6d86beda7c9bf67aaf05053dcbe0b3bcb63968517f gets the materials back but will revert a later change

**Comment by jimsimonz** [comment]
Thanks

**Comment by rdeioris** [comment]
@jimsimonz fixed, thanks again for reporting
