### ISSUE TITLE
Both feet and the right arm's weight is not correct when import metahuman glb

### ISSUE THREAD

**Issue by oncemorego** [rdeioris/glTFRuntime#70]
1. Export metahuman body mesh as f_med_nrw_body.glb
2. Import f_med_nrw_body.glb using glTFRuntime
3. The animation is not right
4. Export the imported skeleton mesh as Transiant_skel_Sequence.glb
5. In Blender, Import Transiant_skel_Sequence.glb,  and check the weight info

Also, Transiant_skel_Sequence.glb has 182448 vertices but the original one f_med_nrw_body.glb only has 32340.
The weight info seems correct in f_med_nrw_body.glb when checking in Blender.

![LoadedMesh](https://github.com/rdeioris/glTFRuntime/assets/1442343/d6c124db-c846-454b-a5be-90bbd5821150)
![LoadingMesh_1](https://github.com/rdeioris/glTFRuntime/assets/1442343/990fa72a-9887-4d4a-8796-9629d61cccd5)
![LoadingMesh_2](https://github.com/rdeioris/glTFRuntime/assets/1442343/2c4995a3-ffc2-412d-a19d-128741c19930)
![VetexWeightInBlender](https://github.com/rdeioris/glTFRuntime/assets/1442343/b612906e-75c0-4925-9549-e8843cc1d008)

Mesh:
[skeleton.zip](https://github.com/rdeioris/glTFRuntime/files/12340570/skeleton.zip)

**Comment by oncemorego** [comment]
Also, Transiant_skel_Sequence.glb has 182448 vertices but the original one f_med_nrw_body.glb only has 32340.
The weight info seems correct in f_med_nrw_body.glb when checking in Blender.

**Comment by rdeioris** [comment]
Hi, thanks for reporting. The asset requires 12 bones influences support and 16bit bone indices (it has more than 256 bones).

Latest master has a patch for it (works only on 5.2), but i am not satisfied with the approach (enabling 16bits blindly will double the amount of gpu memory for every mesh) so i will leave the issue open while i refactor it.

**Comment by oncemorego** [comment]
Thanks for your patch, it works.
