### ISSUE TITLE
StaticMesh Config  Build Simple Collision ,Collision Box incorrect location

### ISSUE THREAD

**Issue by tiantianaixuexi** [rdeioris/glTFRuntime#71]
Hello, when I click Build Simple Collision and set the Pivot Position to the bottom, the position of the collision box is not updated.

It caused collisions to fail in parts of the model

![image](https://github.com/rdeioris/glTFRuntime/assets/31758095/da838791-ece6-4b88-9124-30204a90ac6d)
![image](https://github.com/rdeioris/glTFRuntime/assets/31758095/aa88248e-36ee-40af-ac20-a124af0f0d3c)
![image](https://github.com/rdeioris/glTFRuntime/assets/31758095/4c700982-11f5-41cb-9e53-138a19d02d40)

**Comment by rdeioris** [comment]
Thanks for reporting, should be fixed in latest master.

**Comment by tiantianaixuexi** [comment]
update maset code ,it can work
