### ISSUE TITLE
The metahuman face mesh will tore apart when setting skeletal mesh asset  at runtime 

### ISSUE THREAD

**Issue by oncemorego** [rdeioris/glTFRuntime#75]
1. The issue happens in UE 5.2 with metahuman 5.2 . (It is ok in UE 5.2 with metahuman 5.1)
2. I clear the hairs in metahuman BP_Cooper for clean demonstration
3. Load the face at runtime.
![1](https://github.com/rdeioris/glTFRuntime/assets/1442343/2a597f6f-d1ae-448b-bb35-6ecb8b78840d)
![2](https://github.com/rdeioris/glTFRuntime/assets/1442343/05645605-ff98-46b4-87a1-6c7f026fbcbe)
![3](https://github.com/rdeioris/glTFRuntime/assets/1442343/b4f810eb-3979-482a-8d8c-52edc389e5dd)
![4](https://github.com/rdeioris/glTFRuntime/assets/1442343/929238c5-c146-42af-b245-fcd36a588454)

The BP_Cooper face mesh I exported from UE.
[Cooper_FaceMesh.zip](https://github.com/rdeioris/glTFRuntime/files/12654523/Cooper_FaceMesh.zip)

**Comment by rdeioris** [comment]
Hi, you have an additional bone in the GLB asset (joint0/node0). Just force the root bone to be "root" in the "Force Root Node" option of the SkeletonConfig

**Comment by oncemorego** [comment]
Thanks for your tips.
