### ISSUE TITLE
Material related GC crash

### ISSUE THREAD

**Issue by haowang1013** [rdeioris/glTFRuntime#78]
Hi,

We're seeing some material related GC crash which is caused by not having `FglTFRuntimeParser::ClearCoatMaterialsMap` and `FglTFRuntimeParser::MaterialsNameCache` exposed to the GC collector. Add these 2 lines in `FglTFRuntimeParser::AddReferencedObjects` fixed the crash for us

```
Collector.AddReferencedObjects(ClearCoatMaterialsMap);
Collector.AddReferencedObjects(MaterialsNameCache);
```

Also, to keep things consistent, they should also be cleared in `FglTFRuntimeParser::ClearCache`

**Comment by rdeioris** [comment]
@haowang1013 thanks!
