### ISSUE TITLE
Missing materials in package

### ISSUE THREAD

**Issue by Shumaro211** [rdeioris/glTFRuntime#82]
My model's materials are missing in the package, is working in the editor, I'm importing these with the plugin
![image](https://github.com/rdeioris/glTFRuntime/assets/66711189/a61db776-f9ca-4dd1-a58f-e4d46bef77eb)

I'm using UE5.2

**Comment by Shumaro211** [comment]
Sorry, I just found the ything about including the plugin's content

**Comment by robinwood3d** [comment]
Man, I just got the same issue, but how do you mean including the plugin's content?
