### ISSUE TITLE
5.0.3 doesn't compile

### ISSUE THREAD

**Issue by rk132** [rdeioris/glTFRuntime#88]
Tested on Unreal Version 5.0.3 and Texture->SetPlatformData doesn't exist for the UVolumeTexture class.

https://github.com/rdeioris/glTFRuntime/blob/b352c8c190696b7a7358d24923afc2e2b95ee06c/Source/glTFRuntime/Private/glTFRuntimeParserMaterials.cpp#L424

**Comment by rdeioris** [comment]
fixed in master. Thanks for reporting.
