### ISSUE TITLE
Adding and exposing user metadata in glTF

### ISSUE THREAD

**Issue by faulknermano** [rdeioris/glTFRuntime#89]
Hi @rdeioris, I'd like to ask for advice on the best way to inject user data into a gltf file and have that accessible within UE.

My intention is to add metadata to a node, or perhaps even a mesh:

E.g.
```json
"nodes": [
        {
            "mesh": 0,
            "name": "Hose_low",
            "userdata": "A<<B"
        },
...
```

```json
"meshes": [
        {
            "primitives": [
                {
                    "attributes": {
                        "POSITION": 1,
                        "TANGENT": 2,
                        "NORMAL": 3,
                        "TEXCOORD_0": 4
                    },
                    "indices": 0,
                    "material": 0,
                    "userdata": "A<<B"
                }
            ],
```
In either situation, I was thinking that perhaps it would be exposed in Component Tags?

Is this possible right now? Or perhaps there is another way of doing it?

Thank you!

**Comment by rdeioris** [comment]
The GLTF specs suggest the use of the "extras" object.

glTFRuntime exposes a bunch of utility functions for quickly accessing it (you can check an example here https://github.com/rdeioris/glTFRuntime-docs/blob/master/Tutorials/SkeletonRemapping.md#step-4-remapping-bones-with-json)
