### ISSUE TITLE
KHR_texture_transform

### ISSUE THREAD

**Issue by faulknermano** [rdeioris/glTFRuntime#90]
Hi, is there support for [KHR_texture_transform](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_transform/README.md). I tried injecting the extensions, but I don't think it works.

If it isn't supported, do you plan on supporting in future?

Thanks!

**Comment by rdeioris** [comment]
The extension is fully supported (https://github.com/rdeioris/glTFRuntime/blob/master/Source/glTFRuntime/Private/glTFRuntimeParserMaterials.cpp#L135) but notice that very few exporters have it.

**Comment by faulknermano** [comment]
Thank you Roberto. I will play with a little more; I didn't get expected results the first time, but I might be just doing something wrong. My intention is to post-process gltf files after export using some Python api like pygltflib. But for now, I was just manually inserting the key-values. Thanks again!
