### ISSUE TITLE
After running the project, loading the model error report displays some content

### ISSUE THREAD

**Issue by CX822** [rdeioris/glTFRuntime#95]
LogGLTFRuntime: Error: GetBuffer(): Unable to load buffer 0 from Uri ABeautifulGame.bin (you may want to enable external files loading...)
LogGLTFRuntime: Error: LoadPrimitive(): Unable to load POSITION attribute

**Comment by rdeioris** [comment]
@CX822 Please share the asset, it looks like you are missing the binary part (or it contains errors)

**Comment by CX822** [comment]
https://gitee.com/tomtomzid/3-dmodel/raw/master/ABeautifulGame.gltf
I am using this model, which was downloaded from GitHub

**Comment by CX822** [comment]
> 请共享资产，看起来您缺少二进制部分（或包含错误）

https://gitee.com/tomtomzid/3-dmodel/raw/master/ABeautifulGame.gltf
I am using this model, which was downloaded from GitHub

**Comment by rdeioris** [comment]
This asset is composed by multiple files. You need to download ABeautifulGame.bin too.

I strongly suggest you to use gltf embedded or glb. if you are forced to multiple files asset the (imho) best approach is to zip them (glTFRuntime is able to extract zips on the fly)

**Comment by rdeioris** [comment]
Sorry, not sure to understand, can't you hust download the zipped version of this? https://gitee.com/tomtomzid/3-dmodel/

**Comment by CX822** [comment]
> Sorry, not sure to understand, can't you hust download the zipped version of this? https://gitee.com/tomtomzid/3-dmodel/

Thank you, it's ready to load now
Perhaps I need to ask if there is any log output for the loading time, rendering time, and the size of the loaded model, or how can I output this data
