### ISSUE TITLE
I have purchased the plugin and need your help, The current issue we are facing is

### ISSUE THREAD

**Issue by CX822** [rdeioris/glTFRuntime#96]
1. Download time through URL, model loading time, rendering time
2. Obtain the content of triangles, vertices, and size parts of the downloaded model

**Comment by rdeioris** [comment]
@CX822 please use discord server for help, this is for code issues/bug reports

**Comment by CX822** [comment]
> 请使用 Discord 服务器寻求帮助，这是针对代码问题/错误报告的

Where to reply

**Comment by CX822** [comment]
> 请使用 Discord 服务器寻求帮助，这是针对代码问题/错误报告的

I'm sorry, I don't know where to find help. What contact information would you like to add

**Comment by rdeioris** [comment]
Start by reading docs here: https://github.com/rdeioris/glTFRuntime-docs

If you still have problems after following docs join the discord server and ask for help: https://discord.gg/DzS7MHy
