### ISSUE TITLE
UE4.27 The red and blue renderings are reversed

### ISSUE THREAD

**Issue by Cat-Wong** [rdeioris/glTFRuntime#97]
https://github.com/SpeculativeCoder/UnrealEngine-HTML5-ES3
Use Previous Link build UE Html5, The red and blue renderings are reversed
On the left is a packaged preview, On the right is a preview of the Microsoft 3DViewer viewer
![image](https://github.com/rdeioris/glTFRuntime/assets/28647331/e590bb97-2ecb-49c9-9229-0dcac03f55e5)

**Comment by rdeioris** [comment]
Hi, unfortunately i do not have the resources for supporting third-party builds. As a workaround i can suggest you to patch the material to invert the channels. Are you using the very latest code from the master branch ?

**Comment by Cat-Wong** [comment]
> Hi, unfortunately i do not have the resources for supporting third-party builds. As a workaround i can suggest you to patch the material to invert the channels. Are you using the very latest code from the master branch ?

thank for you reply. i using the code from the master branch, i will try the material to invert the channels, If there are any results, I will reply here

**Comment by Cat-Wong** [comment]
> Hi, unfortunately i do not have the resources for supporting third-party builds. As a workaround i can suggest you to patch the material to invert the channels. Are you using the very latest code from the master branch ?

By the way, how can I reverse the material of the channel in glTFruntime

**Comment by Cat-Wong** [comment]
I reverse the material of the channel in glTFruntime，the display has become correct.
so，I will close this issue
